lib/data/source/ai_source.dart
lib/domain/repository/gemini_repository.dart
lib/domain/repository/video_info_repository.dart
lib/domain/usecase/gemini_usecase.dart
lib/domain/usecase/video_info_usecase.dart
lib/presentation/app/router.dart
lib/presentation/ui/audio_page/audio_page.dart
lib/presentation/ui/splash/splash.dart
lib/presentation/ui/test_page/testpage.dart
lib/presentation/widgets/audio_player/audio_player.dart
lib/presentation/widgets/audio_player/audio_player_view_model.dart
pubspec.lock
pubspec.yaml

Feature/recomment UI

---

analysis_options.yaml
lib/data/dto/mania/maniadb_artist_dto.dart
lib/data/dto/mania/maniadb_song_dto.dart
lib/data/dto/naver_search_dto.dart
lib/data/repository_impl/maniadb_repository_impl.dart
lib/data/source/manidb/maniadb_data_source.dart
lib/data/source/manidb/maniadb_data_source_impl.dart
lib/data/source/naver/naver_search_data_source.dart
lib/domain/entitiy/maniadb/maniadb_artist_entity.dart
lib/domain/entitiy/maniadb/maniadb_song_entity.dart
lib/domain/repository/maniadb_repository.dart
lib/domain/usecase/maniadb/maniadb_artist_usecase.dart
lib/domain/usecase/maniadb/maniadb_song_usecase.dart
lib/presentation/app/router.dart
lib/presentation/ui/search/search.dart
lib/presentation/ui/search/search_result.dart
lib/presentation/ui/search/widgets/search_area.dart
pubspec.lock
pubspec.yaml
test/maniadb/maniadb_data_source_impl_test.dart

maniadb 가수이름, 곡명으로 검색하는 로직
네이버 api로 가사 검색기능 진행중

[feat]maniadb 연동, 네이버api연결 진행중

---

lib/data/repository_impl/gemini_repository_impl.dart
lib/data/repository_impl/play_list_repository_impl.dart
lib/domain/usecase/login/apple_login_use_case.dart
lib/presentation/app/router.dart
lib/presentation/ui/recommend_page/recommend_page_condition_one.dart
lib/presentation/ui/recommend_page/recommend_page_condition_two.dart
lib/presentation/ui/recommend_page/view_model/condition_view_model.dart
lib/presentation/widgets/loading/loading_view_model/loading_view_model.dart
lib/presentation/widgets/loading/loading_widget.dart
test/gemini_test.dart
test/google_login_data_source_impl_test.mocks.dart

[Feat] : loading 화면 추가, 음악 추천 로직 추가중 #5

---

lib/data/dto/play_list_dto.dart
lib/data/repository_impl/play_list_repository_impl.dart
lib/domain/entitiy/play_list_entity.dart
lib/domain/repository/play_list_repository.dart
lib/domain/usecase/play_list_usecase.dart
lib/presentation/theme/theme.dart
lib/presentation/ui/saved/saved_page.dart
lib/presentation/ui/saved/view_models/playlist_view_model.dart
lib/presentation/ui/saved/widgets/play_list.dart
lib/presentation/ui/saved/widgets/saved_tab_button.dart

- 플레이리스트 페이지 상단 ui 제작
- 라이브러리 / 플레이리스트 중 플레이리스트 선택 시 보이는 리스트뷰 제작
- 뷰모델 제작
- 아직 데이터 연결은 안 됐습니다

18 featplaylist UI prep

---

lib/data/source/spotify/spotify_data_source_impl.dart
lib/presentation/providers/login/providers.dart
lib/presentation/ui/recommend_page/view_model/condition_view_model.dart
test/spotify_data_source_impl_test.dart

[Feat] : 스포티파이 provider 추가 #5

---

lib/data/dto/raw_song_dto.dart
lib/data/repository_impl/raw_song_repository_impl.dart
lib/data/source/saved/library_source.dart
lib/data/source/saved/library_source_impl.dart
lib/data/source/saved/play_list_source_impl.dart
lib/data/source/saved/raw_song_source_impl.dart
lib/data/util/duration_parse.dart
lib/domain/entitiy/raw_song_entity.dart
lib/domain/entitiy/video_info_entitiy.dart
lib/presentation/ui/saved/widgets/play_list.dart

- playlist와 library 리스트 형태로 받아오게 수정
- 인기순위 측정용 데이터 countLibrary, countPlaylist 추가
- firebase에 duration 업로드할 수 있도록 durationParse() 함수 생성하고 VideoInfoEntity에서 사용
- 나중에 리팩토링할 시간이 있다면 dto로 분리해도 좋을 듯
- createLibrary, deleteLibrary 생성

54 featplaylist

---

lib/data/dto/library_dto.dart
lib/domain/entitiy/library_entity.dart
lib/presentation/ui/recommend_page/view_model/save_song_bottom_sheet_view_model.dart
lib/presentation/ui/saved/pages/saved_page.dart
lib/presentation/ui/saved/view_models/library_view_model.dart
lib/presentation/ui/saved/view_models/list_sort_viewmodel.dart
lib/presentation/ui/saved/widgets/library.dart
lib/presentation/ui/saved/widgets/saved_tab_button.dart

- DB/Library collection에 artist, title, imgUrl 데이터 추가했습니다
- 최대한 추가 안해보려고 했는데, 데이터가 이미 들어가있는 쪽이 훨씬 효율적인거같아요
- 라이브러리 정렬 기능
- 버튼 디자인, 눌렀을 때 반응 등 자잘한 디자인 수정

66 featplaylist play

---

lib/data/repository_impl/raw_song_repository_impl.dart
lib/data/source/saved/raw_song_source.dart
lib/data/source/saved/raw_song_source_impl.dart
lib/domain/repository/saved/raw_song_repository.dart
lib/domain/usecase/raw_song_usecase.dart

- 사용법 : rawSongUsecaseProvider를 ref로 읽어서 .updateVideo(RawSongEntity) 사용하시면 됩니다
- DB에 Song 저장하고 countPlaylist 증가시키는 함수 기능 추가

feat: updateVideo 함수 생성

---

lib/presentation/ui/saved/pages/playlist_page.dart

feat: 셔플 재생 기능

---

README.md
lib/presentation/ui/search/search.dart

[doc] : readme 수정 #5

---

README.md

[Docs] : Readme 작성 #5

---

lib/presentation/ui/recommend_page/widgets/recommend_exit_alert_dialog.dart
lib/presentation/ui/recommend_page/widgets/save_playlist_bottom_sheet.dart
lib/presentation/ui/saved/pages/edit_playlist_page.dart
lib/presentation/ui/saved/pages/playlist_page.dart
lib/presentation/ui/saved/widgets/card_widget_library.dart
lib/presentation/ui/saved/widgets/delete_alert_dialog.dart
lib/presentation/ui/saved/widgets/play_list.dart

- 재생기능 롤백
- 라이브러리 메모 화면에 버튼 스타일 변경
- 전체적으로 취소버튼 색상 회색으로 변경
- 플레이리스트 편집 페이지 탈출 조건 수정

fix: 디자인 수정

---

lib/presentation/ui/search/search.dart
lib/presentation/ui/search/widgets/bottomSheet/search_lyics_bottom_sheet.dart
lib/presentation/ui/search/widgets/bottomSheet/search_song_bottom_sheet.dart
lib/presentation/widgets/audio_player/audio_player_bottomsheet.dart

[Fix] : search 로딩부분 수정 #5

---

lib/presentation/ui/recommend_page/widgets/save_song_bottom_sheet.dart

[Fix] : 바텀시트 키보드 패딩 추가 #5

---

lib/presentation/ui/saved/pages/playlist_page.dart
lib/presentation/ui/saved/pages/saved_page.dart
lib/presentation/ui/search/search.dart

[Fix] : scrolledElevation 수정 #5

---

ios/Podfile.lock
lib/main.dart

138 featscreen direct lock

---

lib/main.dart

[Fix] : main 중복코드 삭제 #5

---

lib/data/repository_impl/library_repository_impl.dart
lib/data/repository_impl/login/delete_user_repository_impl.dart
lib/data/repository_impl/play_list_repository_impl.dart
lib/data/source/firebase_songs/library_source.dart
lib/data/source/firebase_songs/library_source_impl.dart
lib/data/source/firebase_songs/play_list_source.dart
lib/data/source/firebase_songs/play_list_source_impl.dart
lib/domain/repository/saved/library_repository.dart
lib/domain/repository/saved/play_list_repository.dart
lib/domain/usecase/library_usecase.dart
lib/domain/usecase/login/delete_user_usecase.dart
lib/domain/usecase/play_list_usecase.dart
lib/presentation/ui/login/login_view_model.dart
lib/presentation/ui/saved/pages/playlist_page.dart
lib/presentation/ui/saved/pages/saved_page.dart
lib/presentation/ui/saved/view_models/playlist_view_model.dart
lib/presentation/ui/saved/widgets/play_list.dart
lib/presentation/ui/saved/widgets/sorted_type_box.dart
lib/presentation/ui/search/widgets/bottomSheet/search_lyics_bottom_sheet.dart
lib/presentation/ui/settings_page/revoke_page.dart
lib/presentation/ui/splash/splash.dart

- 로그아웃 시 user_uid 초기화
- 회원탈퇴 시 곡 정보 삭제

fix: 로그아웃 로직 수정

---

README.md
analysis_options.yaml
lib/data/source/firebase_songs/library_source_impl.dart
lib/data/source/firebase_songs/play_list_source_impl.dart
lib/data/source/firebase_songs/raw_song_source_impl.dart
lib/data/source/gemini_source_impl.dart
lib/data/source/login/apple_login_data_source_impl.dart
lib/data/source/login/delete_user_data_source_impl.dart
lib/data/source/login/google_login_data_source_impl.dart
lib/data/source/login/kakao_login_data_source_impl.dart
lib/data/source/naver/naver_search_data_source_impl.dart
lib/domain/usecase/login/apple_login_use_case.dart
lib/domain/usecase/login/delete_user_usecase.dart
lib/domain/usecase/login/google_login_use_case.dart
lib/domain/usecase/login/kakao_login_usecase.dart
lib/presentation/app/router.dart
lib/presentation/ui/login/login_view_model.dart
lib/presentation/ui/saved/pages/saved_page.dart
lib/presentation/ui/saved/widgets/sorted_type_box.dart
lib/presentation/ui/search/widgets/search_area.dart
lib/presentation/ui/search/widgets/search_word_page.dart
lib/presentation/ui/settings_page/settings_page.dart
lib/presentation/ui/settings_page/version_view_model.dart
lib/presentation/widgets/audio_player/audio_player_view_model.dart
test/maniadb/maniadb_data_source_impl_test.dart
test/maniadb/maniadb_repository_impl_test.dart
test/naver_data_source_impl_test.dart
test/spotify_data_source_impl_test.dart

[Fix] : 파란줄 제거 #5

---

lib/presentation/ui/saved/pages/edit_playlist_page.dart
lib/presentation/ui/saved/pages/playlist_page.dart
lib/presentation/ui/saved/pages/saved_page.dart
lib/presentation/ui/saved/widgets/library.dart
lib/presentation/ui/saved/widgets/play_list.dart

- 오디오 플레이어에 리스트 가려지지 않게 공백 추가
- 오디오 플레이어 틀기 전에 togleStop

feat/플레이리스트 오디오 관련 수정

---

lib/presentation/ui/saved/pages/playlist_page.dart
lib/presentation/ui/saved/widgets/library.dart
lib/presentation/ui/search/widgets/bottomSheet/lyrics_page.dart
lib/presentation/ui/search/widgets/result/search_result_spotify.dart

[Feat] : ListView 들 밑 공백에 MUOZ 로고 추가 #5

---

lib/data/repository_impl/video_info_repository_impl.dart
lib/presentation/ui/ranking_page/widgets/speech_bubble_widget.dart
lib/presentation/ui/recommend_page/recommend_page.dart
lib/presentation/ui/recommend_page/recommend_page_condition_two.dart
lib/presentation/ui/recommend_page/view_model/condition_view_model.dart
lib/presentation/ui/saved/pages/playlist_page.dart
lib/presentation/ui/saved/widgets/play_list.dart
lib/presentation/ui/search/widgets/bottomSheet/search_lyics_bottom_sheet.dart
lib/presentation/ui/search/widgets/bottomSheet/search_song_bottom_sheet.dart
lib/presentation/widgets/audio_player/audio_player_view_model.dart
lib/presentation/widgets/toast_message/toast_message.dart

toggleStop 에 await 걸기
AudioUrl 값이 모종의 이유로 안들어 오는 경우 대응 1차

[Fix] : Video Url 이 empty 가 들어오는 경우, 대응 #5

---

lib/presentation/widgets/audio_player/audio_player_view_model.dart

[Fix] : 오디오 플레이어 currentSong 디폴트값 변경 #5

---

README.md

Docs/search readme 추가

---

lib/data/repository_impl/video_info_repository_impl.dart
lib/presentation/ui/ranking_page/ranking_page.dart
lib/presentation/widgets/audio_player/audio_player_view_model.dart

[Fix] : 리펙토링 일부#5

---

lib/presentation/ui/saved/widgets/library.dart

[Fix] : 보관함 BottomModal 높이 수정 #5

---

lib/presentation/ui/recommend_page/recommend_page_condition_two.dart
lib/presentation/ui/recommend_page/view_model/condition_view_model.dart
lib/presentation/ui/recommend_page/widgets/save_playlist_bottom_sheet.dart
lib/presentation/ui/recommend_page/widgets/save_song_bottom_sheet.dart

음악 카드 추천 속도 단축
추천시 가장 시간을 많이 잡아먹던 video 불러오는 로직을 스킵하고,
재생하거나 저장시 필요할때 로딩하는 방식으로 바꿈

[Fix] : 음악 카드 추천 속도 단축 #5

---

lib/presentation/ui/recommend_page/recommend_page.dart
lib/presentation/ui/recommend_page/recommend_page_condition_one.dart
lib/presentation/ui/recommend_page/recommend_page_condition_two.dart
lib/presentation/ui/recommend_page/view_model/condition_view_model.dart
lib/presentation/ui/recommend_page/widgets/text_box_widgets.dart
lib/presentation/widgets/audio_player/audio_player_bottomsheet.dart
lib/presentation/widgets/home_tap/home_bottom_navigation.dart
lib/presentation/widgets/toast_message/toast_message.dart

[Fix] : UT 수정 1차 #5

---

lib/presentation/widgets/speech_ballon/speech_ballon.dart

[Fix] : 말풍선 nip 수정 #5

---

lib/presentation/app/router.dart
lib/presentation/ui/home/home_page.dart
lib/presentation/ui/ranking_page/ranking_page.dart
lib/presentation/ui/recommend_page/recommend_page.dart
lib/presentation/ui/recommend_page/recommend_page_condition_one.dart
lib/presentation/ui/recommend_page/recommend_page_condition_two.dart
lib/presentation/ui/saved/pages/edit_playlist_page.dart
lib/presentation/ui/saved/pages/library_page.dart
lib/presentation/ui/saved/pages/playlist_page.dart
lib/presentation/ui/saved/pages/saved_page.dart
lib/presentation/ui/search/search.dart

1. GoRouter안에서 bottomNavigationBar가 있는 페이지를 shellRoute로 설정
2. 개별화면에 할당된 bottomNavigationBar 제거

[fix]BottomNavigation UI 수정

---

lib/presentation/ui/home/home_page.dart
lib/presentation/ui/ranking_page/ranking_page.dart
lib/presentation/ui/recommend_page/recommend_page.dart
lib/presentation/ui/recommend_page/recommend_page_condition_one.dart
lib/presentation/ui/recommend_page/recommend_page_condition_two.dart
lib/presentation/ui/recommend_page/widgets/recommend_exit_alert_dialog.dart
lib/presentation/ui/saved/pages/edit_playlist_page.dart
lib/presentation/ui/saved/pages/library_page.dart
lib/presentation/ui/saved/pages/playlist_page.dart
lib/presentation/ui/saved/pages/saved_page.dart
lib/presentation/ui/search/search.dart

[Fix] : RecommendExitAlertDialog 버그 수정

[Fix] : RecommendExitAlertDialog 버그 수정

---

lib/presentation/widgets/audio_player/audio_player_bottomsheet.dart

[Fix] : 오디오 플레이어 이미지 오류 수정 #5

---

lib/presentation/ui/saved/pages/playlist_page.dart
lib/presentation/ui/saved/widgets/menu_bottom_sheets.dart

[Fix] : 플레이리스트 이미지 null 예외처리 #5

---

pubspec.yaml

[Fix] : version up

---

lib/presentation/ui/recommend_page/widgets/save_playlist_bottom_sheet.dart
lib/presentation/ui/search/widgets/bottomSheet/search_song_bottom_sheet.dart
pubspec.yaml

Sentry로 날라온 또 다른 버그 수정
해당 바텀시트에서 곡 저장시 빠르게 클릭했을 경우 발생하는 ref.dispose 문제 관련 해결

[Fix] : search_song_bottom_sheet 의 연속 클릭으로 인한 버그 수정 #5

---

lib/presentation/ui/search/widgets/bottomSheet/search_song_bottom_sheet.dart
lib/presentation/ui/search/widgets/result/search_result_spotify.dart

임시조치
음악 로딩중에 배경화면 누르면 창이 꺼져 ref 쪽 문제가 생기는 문제 해결

[Fix] : search_song_bottom_sheet 버그 2차 수정 #5
